/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.ine5605.trabalho1.apresentacao;

import br.ufsc.ine5605.trabalho1.controle.ControladorUrna;
import br.ufsc.ine5605.trabalho1.entidade.Candidato;
import br.ufsc.ine5605.trabalho1.entidade.Urna;
import java.awt.Font;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 *
 * @author Guilherme
 */
public class TelaResultadoEleicao extends javax.swing.JFrame {

    private ControladorUrna controlador;

    public TelaResultadoEleicao(ControladorUrna controlador) {
        this.controlador = controlador;
        initComponents();
        imprimeResultado();
        setLocationRelativeTo(null);
        texto_Resultado.setFont(new Font("Consolas", Font.PLAIN, 16));

    }

    public void imprimeResultado() {

        for (Urna urna : controlador.getLista()) {
            insereTexto(String.format("Seção: %1$d Zona: %2$d Cidade: %3$s\n", urna.getSecaoEleitoral(), urna.getZonaEleitoral(), urna.getCidade().getNome()));
            insereTexto("--------------- Vereadores ---------------\n");
            LinkedHashMap<Candidato, Integer> vereadores = controlador.getVariavelMaisVotada(urna.getTotalDeVotosPorVereador());
            for (Entry<Candidato, Integer> entry : vereadores.entrySet()) {
                insereTexto(entry.getKey().getNome() + "  (" + entry.getValue() + " votos)\n");
            }

            insereTexto("--------------- Prefeitos  ---------------\n");
            LinkedHashMap<Candidato, Integer> prefeitos = controlador.getVariavelMaisVotada(urna.getTotalDeVotosPorPrefeito());
            for (Entry<Candidato, Integer> entry : prefeitos.entrySet()) {
                insereTexto(entry.getKey().getNome() + "  (" + entry.getValue() + " votos)\n");
            }

            insereTexto("------------------------------------------\n");

        }
        insereTexto("-------------- Vencedores ----------------\n");
        insereTexto(String.format("Prefeito vencedor: %1$s\n", (controlador.prefeitoVencedor().value1.getNome() + " (" + controlador.prefeitoVencedor().value2 + " votos)")));
        insereTexto("Vereadores: %1$s\n");
        System.out.println(controlador.prefeitoVencedor().value1.getNome() + " " + controlador.prefeitoVencedor().value2);
    }

    public void insereTexto(String txt) {
        texto_Resultado.append(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto_Resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado");

        texto_Resultado.setColumns(20);
        texto_Resultado.setRows(5);
        jScrollPane1.setViewportView(texto_Resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto_Resultado;
    // End of variables declaration//GEN-END:variables
}
